name: tst

on:
  push:
    branches:
      - '^2[0-9].[0-9]{1,2}-(PRD|prd|AR|ar|TD|td)-[0-9]{3,5}'
      - 'master'
  pull_request:
    branches:
      - '^(PRD|prd|AR|ar|TD|td)-[0-9]{3,5}'
      - '^2[0-9].[0-9]{1,2}-(PRD|prd|AR|ar|TD|td)-[0-9]{3,5}'
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

